
export const courses = [
  {
    name: "APC 300 - Programming I",
    description: "Java. Program design and implementation, debugging and testing, simple data types, conditionals, loops, and methods.",
    githubIcon: true,
    courseLink: "https://github.com/maggiemay-afk/introToJava",
    courseLinkDesc: "View my course work on GitHub",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 310 - Math (for computer science)",
    description: "Logic sets, functions, reasoning, probability, relations, graphs, trees, Boolean algebra, algorithms.",
    githubIcon: false,
    courseLink: "",
    courseLinkDesc: "",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 340 - Legal and Ethical Responsibilities",
    description: "Legal and ethical considerations associated with developing software and information systems. Topics include data privacy, intellectual property, and compliance with regulatory requirements.",
    githubIcon: false,
    courseLink: "",
    courseLinkDesc: "",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 350 - Programming II",
    description: "Java. Methods, file IO, arrays, abstract data types, classes, GUIs, inheritance, composition.",
    githubIcon: true,
    courseLink: "https://github.com/maggiemay-afk/progTwoJava",
    courseLinkDesc: "View my course work on GitHub",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 360 - Database Management I",
    description: "SQL. Design and implementation of relational databases. Data modeling techniques including entity-relationships, database normalization, and querying features.",
    githubIcon: false,
    courseLink: "",
    courseLinkDesc: "",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 370 - Systems Analysis and Design",
    description: "Systems development life cycle including scope definition, problem analysis, requirements analysis, logical design, and decision analysis. Other topics include use case development, gap analysis, financial analysis, feasibility analysis",
    githubIcon: false,
    courseLink: "",
    courseLinkDesc: "",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 380 - Project Management Techniques",
    description: "Introduction to project management tools and techniques, including project selection, project life cycle, stakeholder management, scope management, budget management, scheduling, quality management, risk identification, and procurement management.",
    githubIcon: false,
    courseLink: "",
    courseLinkDesc: "",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 390 - Object Oriented Programming",
    description: "Java. Object-Oriented programming techniques. Classes, interfaces, exception handling, inheritance, polymorphism, overloading, abstract classes and methods, serialization, generics, and recursion.",
    githubIcon: true,
    courseLink: "https://github.com/maggiemay-afk/objectOrientedProgramming",
    courseLinkDesc: "View my course work on GitHub",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 400 - Applied Communication Networks",
    description: "Design, configuration, and problem solving of computer networks. Topics include TCP/IP and OSI architecture, application layer, transport layer, network layer, data link, and physical layers.",
    githubIcon: false,
    courseLink: "",
    courseLinkDesc: "",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 410 - Database Management II",
    description: "MongoDB, Apache Cassandra. Non-relational (NoSQL) databases such as document, graph, key-value, and wide column databases. Topics include data types, CRUD (create, read, update, delete) functions, queries, cursors, indexing, dynamic schema design, scalability, analysis of data, and data security.",
    githubIcon: false,
    courseLink: "",
    courseLinkDesc: "",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 420 - Computer Security I",
    description: "Java. Topics cover security and risk management, security engineering, identity and access management, security operations, cryptography, access control models, malicious software, security policies, security models, trust, vulnerability assessment, security standards and evaluation, and secure storage.",
    githubIcon: true,
    courseLink: "https://github.com/maggiemay-afk/CompSec",
    courseLinkDesc: "View my course work on GitHub",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 430 - Applied Data Structures and Algorithms",
    description: "Java. Abstract data types, dynamic arrays, iterators, linked lists, generics, stacks, queues, binary search tree, collections, maps, hashing, graphs, sorting, graphics, web programming, and user interfaces.",
    githubIcon: true,
    courseLink: "https://github.com/maggiemay-afk/data-structures",
    courseLinkDesc: "View my course work on GitHub",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 440 - Web Development",
    description: "HTML, CSS, JavaScript, Bootstrap, Python, Django, web services, and database integration.",
    githubIcon: true,
    courseLink: "https://github.com/maggiemay-afk/webDev",
    courseLinkDesc: "View my course work on GitHub",
    projectLink: "https://github.com/maggiemay-afk/djangoProject",
    projectLinkDesc: "View my Django project on GitHub",
  },
  {
    name: "APC 450 - Operating Systems",
    description: "Topics covered include processes, threads, scheduling, concurrency control, memory management, and systems programming using POSIX API.",
    githubIcon: false,
    courseLink: "",
    courseLinkDesc: "",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 460 - Software Engineering Practices",
    description: "Java. Topics covered include waterfall, iterative and agile approaches to software development, IDEs, unified modeling language (UML), testing frameworks, requirement analysis, object-oriented analysis, test-driven development, and design patterns.",
    githubIcon: false,
    courseLink: "",
    courseLinkDesc: "",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 490 - Capstone Project Preperation",
    description: "Review of software engineering practices, project management techniques, systems analysis, communication, and project selection and planning.",
    githubIcon: false,
    courseLink: "",
    courseLinkDesc: "",
    projectLink: false,
    projectLinkDesc: "",
  },
  {
    name: "APC 495 - Capstone Project (Spring 2024)",
    description: "Updates to Ambiance.dev including: Initialize Firestore database, create administrative UI, enable authentication, add API routes, and more.",
    githubIcon: true,
    courseLink: "https://github.com/hermanator608/ambiance",
    courseLinkDesc: "See my progress on GitHub",
    projectLink: false,
    projectLinkDesc: "",
  },
]